from os import environ

MONGO_SERVER = environ['MONGO_SERVER']
MONGO_USER = environ['MONGO_USER']
MONGO_PASSWORD = environ['MONGO_PASSWORD']
CONTRACT_ADDRESS = environ['CONTRACT_ADDRESS']
APP_ADDRESS = environ['APP_ADDRESS']
CONTRACT_PROVIDER = environ['CONTRACT_PROVIDER']
